QD_file: C:\Users\admin\Documents\GitHub\Quela_Qblox\qblox_drive_AS\QD_backup\20250330\DRKE#242_SumInfo.pkl
Comments: ---

RO-atte = 0 dB
XY-atte = 0 dB
Reset time = 250 us

[q0]
    bare   = 0.0 GHz
    ROF    = 6.0 GHz
    RO-amp = 0.5 V
    ROT    = 1.0 us
    XYF    = 4.0 GHz
    Pi-amp = 0.05 V
    Pi-dura= 40.0 ns
    x      = 6000.0 MHz
    g      = 0.0 MHz

[q1]
    bare   = 0.0 GHz
    ROF    = 6.0 GHz
    RO-amp = 0.5 V
    ROT    = 1.0 us
    XYF    = 4.0 GHz
    Pi-amp = 0.05 V
    Pi-dura= 40.0 ns
    x      = 6000.0 MHz
    g      = 0.0 MHz

[q2]
    bare   = 0.0 GHz
    ROF    = 6.0 GHz
    RO-amp = 0.5 V
    ROT    = 1.0 us
    XYF    = 4.0 GHz
    Pi-amp = 0.05 V
    Pi-dura= 40.0 ns
    x      = 6000.0 MHz
    g      = 0.0 MHz

[q3]
    bare   = 0.0 GHz
    ROF    = 6.0 GHz
    RO-amp = 0.5 V
    ROT    = 1.0 us
    XYF    = 4.0 GHz
    Pi-amp = 0.05 V
    Pi-dura= 40.0 ns
    x      = 6000.0 MHz
    g      = 0.0 MHz

